### ISSUE TITLE
TypeError: dest.on is not a function

### ISSUE THREAD

**Issue by biddster** [clineamb/gulp-s3-upload#38]
I've dropped the plugin in, using node 4.3.2, Gulp, CLI version 1.2.1, Local version 3.9.1.

My upload task looks like this:

```
$.util.log(`S3 upload to profile [${process.env.AWS_PROFILE}]`);
    gulp.src(["./S3/config/*.json"])
        .pipe($.s3Upload({
            Bucket: 'a bucket',
            ACL: 'public-read',
            Metadata: {
                'Content-Type': 'application/json',
                'Cache-Control': 'public, max-age=3600'
            }
        }));
```

My attempt to upload fails with the following error:

```
[00:29:39] TypeError: dest.on is not a function
    at DestroyableTransform.Readable.pipe (/Users/luke/git/roc/roc-aws/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:516:8)
    at Gulp.<anonymous> (/Users/luke/git/roc/roc-aws/gulpfile.js:37:10)
```

Have I missed something obvious?

**Comment by chimmelb** [comment]
Just got the same error. Any thoughts?

````
chimmelb$ aws --version
aws-cli/1.10.36 Python/2.7.10 Darwin/15.5.0 botocore/1.4.26
chimmelb$ gulp -v
[14:15:54] CLI version 3.9.1
[14:15:54] Local version 3.9.1
chimmelb$ node -v
v6.2.0
````

**Comment by chimmelb** [comment]
Heh, just found it. It's the gulp importer, I'm using the same thing. Transforms `gulp-s3-upload` (and all other gulp packages) to `$.s3Upload`. As per the docs, the s3-upload package must be initialized (event with an empty config value).

My code changed to this: 

````
.pipe($.s3Upload()({
        Bucket: 'buckeroo', //  Required 
        ACL: 'public-read' //  Needs to be user-defined 
      }, {
        // S3 Construcor Options, ie: 
        maxRetries: 5
      }));
````

Note the `$.s3Upload()({` line. Needed to initialize the library, then use it.

**Comment by clineamb** [comment]
@biddster I hope @chimmelb's works for you?
