### ISSUE TITLE
dest.on is not a function at DestroyableTransform.Readable.pipe

### ISSUE THREAD

**Issue by craigharvi3** [clineamb/gulp-s3-upload#47]
Hey,

I'm getting the following error when running this code:

```
const gulp = require('gulp');
const s3 = require('gulp-s3-upload');
const config = require('../config');

gulp.task('s3-assets', function () {
  gulp.src(config.paths.assets + '/css/**')
    .pipe(s3({
      Bucket: config.s3.bucket,
      ACL: config.s3.acl,
      keyTransform: function(filename) {
        var newKey = "folder/" + filename;
        return newKey;
      }
    }));
});
```

which throws the following error:

```
TypeError: dest.on is not a function
    at DestroyableTransform.Readable.pipe (MYFOLDER/node_modules/gulp/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:516:8)
    at Gulp.<anonymous> (MYFOLDER/gulp/tasks/s3-assets.js:19:4)
    at module.exports (MYFOLDER/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (MYFOLDER/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (MYFOLDER/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (MYFOLDER/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:46:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:607:11)
```
I'm using the `~/.aws/credentials` way of authorising s3.

Cheers

Craig.

**Comment by craigharvi3** [comment]
Ahh, figured out the issue, you need to initialise `s3` before using it, i.e:

```
const s3 = require('gulp-s3-upload')();
```
